import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./components/Navbar";
import { Toaster } from "@/components/ui/sonner"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"], // أضف 900
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${roboto.variable} font-roboto antialiased`}>
          <Navbar />
          {children}
           <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
